### PR TITLE
Pya 40 feature integration of api to UI

### PR DESCRIPTION
**Pull request by cristoph143**
### PR Description: Enhance Event Page with Improved Error Handling and Layout Adjustments

**Overview:**
This pull request enhances the event page by adding placeholders for error and no events, centering the content, and improving the layout. These changes ensure a better user experience by providing appropriate feedback when events are not available and making the page layout more appealing.

**Key Changes:**
1. **Error and No Events Placeholders:**
   - Added placeholders to display messages when there are no upcoming events or when an error occurs during data retrieval.
   - Updated the `get_upcoming_events` function in `views.py` to handle and display error messages and no events messages appropriately.

2. **Event Data Fetching and Parsing:**
   - Improved the `fetch_events` function to handle API responses more robustly.
   - Added sample event data for testing purposes.

3. **CSS Adjustments:**
   - Added new CSS classes to handle various layout and styling changes, including:
     - Centering elements.
     - Setting heights and widths for containers.
     - Adding padding and margin utilities.

4. **Template Updates:**
   - Modified `event_page_test2.html` to include the new placeholders and updated content structure.
   - Introduced `events-test3.html` and `hero-test3.html` partials to display event details and placeholders dynamically.
   - Added tooltips and improved the overall styling for event cards.

5. **JavaScript Enhancements:**
   - Added a script in `hero-test3.html` to handle dynamic content updates and navigation between events using arrow keys or buttons.
   - Improved the script to display appropriate messages and images based on the fetched event data or placeholders in case of errors or no events.

**Testing:**
- Verified that error messages and no events messages are displayed correctly when applicable.
- Ensured that the layout adjustments are responsive and visually appealing across different screen sizes.
- Tested the dynamic content updates and navigation functionality in `hero-test3.html`.

### CODE REVIEW

**Comment by Luzefiru** [comment]
Please create a route handler for `/favicon.ico` and an image using the PizzaPy logo using [favicon.io](https://favicon.io/). Also, consider adding routes for:
- `/opengraph-image.jpg`
- `/twitter-image.jpg`

So that social embeds when sharing the links have a nice image of the website.

**Comment by Luzefiru** [comment]
> Event Data Fetching and Parsing:
> Improved the fetch_events function to handle API responses more robustly.
> Added sample event data for testing purposes.

Is it possible for us to start integrating the meetup data instead of placeholders, @cristoph143?

**Comment by Luzefiru** [comment]
Some things that should be adjusted for mobile responsiveness at `320px` width:

### Landing Page Typography

The text is too big at the moment. Try using breakpoints to make the text scale better on smaller screens so that more content fits on the page.

image

### Footer Text Wrapping on Tablets (`768px`)

The text should ideally fit on one line. Perhaps you can adjust the grid columns so that the left side occupies more space on this specific breakpoint?

image

Other than the comments I made previously, the site LGTM. Good work @cristoph143!

**Comment by jackjk521** [comment]
Code Review: 
Events Page:
- Add margin on the upcoming events card as it is too tight on the left and right sides
image

Nav bar:
- Contact Us - should redirect to the  https://www.facebook.com/PizzaPy.PH (FB Page)

Footer:
- Make the following have no hover effect just plain white ( PizzaPy © 2025
, Terms of Service, 
Privacy Policy )
- Update the following social media links: 
FB - https://www.facebook.com/PizzaPy.PH,
Meetup - https://www.meetup.com/pizzapy-ph/events/
github - https://github.com/pizzapy

**Comment by cristoph143** [comment]
> Please create a route handler for `/favicon.ico` and an image using the PizzaPy logo using [favicon.io](https://favicon.io/). Also, consider adding routes for:
> 
> * `/opengraph-image.jpg`
> * `/twitter-image.jpg`
> 
> So that social embeds when sharing the links have a nice image of the website.

**Comment by cristoph143** [comment]
[favicon_io.zip](https://github.com/user-attachments/files/16246777/favicon_io.zip)

**Pull request merged**
